name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: mvn clean package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ./app-jar

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          source: "./app-jar/*.jar"
          target: "/home/ec2-user/app/"

      - name: Restart App on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          script_stop: false
          script: |
            echo "Parando app anterior se existir..."
            pkill -f 'GymMembership' || true

            echo "Pegando último JAR enviado..."
            JAR_NAME=$(ls /home/ec2-user/app/*.jar | tail -n 1)

            echo "Iniciando app com variáveis do banco..."
            export DB_URL="${{ secrets.DB_URL }}"
            export DB_USERNAME="${{ secrets.DB_USERNAME }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"

            nohup java -jar \
              -Dspring.datasource.url=$DB_URL \
              -Dspring.datasource.username=$DB_USERNAME \
              -Dspring.datasource.password=$DB_PASSWORD \
              $JAR_NAME > /home/ec2-user/app/app.log 2>&1 &
