name: CI/CD Pipeline #pipeline for deploying to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

#      - run: mvn clean verify
      - run: mvn clean package -DskipTests

      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/GymMembership-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: .

      - run: ls -lR app-jar  # debugging line to list contents

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          source: "GymMembership-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/app/"


      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          script_stop: false
          script: |
            pkill -f 'GymMembership-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar /home/ec2-user/app/GymMembership-0.0.1-SNAPSHOT.jar > /home/ec2-user/app/app.log 2>&1 &

