name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: mvn clean verify
      - run: mvn package -DskipTests

      - uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/GymMembership-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-jar

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          ssh-passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          source: "app-jar/GymMembership-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/app/"

      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          script: |
            pkill -f 'GymMembership-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar /home/ec2-user/app/GymMembership-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
