name: CI/CD Pipeline #pipeline para deploy na AWS EC2 da minha aplicação Java Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

#      - run: mvn clean verify
      - run: mvn package -DskipTests

      - uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/GymMembership-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-jar

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          source: "app-jar/*"
          target: "/home/ec2-user/app/"

      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          script: |
            pkill -f 'GymMembership-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar /home/ec2-user/app/GymMembership-0.0.1-SNAPSHOT.jar > app.log 2>&1 &